crudforge:
    resource: "@CrudforgeBundle/Controller/"
    type:     annotation
    prefix:   /
    
crudforge_routing:
    resource: "@CrudforgeBundle/Resources/config/routing.yml"

crudforge_routing_start:
    resource: "@CrudforgeBundle/Resources/config/routing_start.yml"

schemas:
    pattern: /schemas
    defaults:  { _controller: CrudforgeBundle:Document:index }

schema:
    pattern: /schema/{document_id}
    defaults:  { _controller: CrudforgeBundle:Fields:list }
  
schema_action:
    pattern: /schema_action/{prefix}/{type}
    defaults:  { _controller: CrudforgeBundle:Document:getSchema }

share:
    pattern: /share/{document_id}
    defaults:  { _controller: CrudforgeBundle:Shares:list }

login:
    pattern: /login
    defaults:  { _controller: CrudforgeBundle:Default:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout  
    defaults: { _controller: CrudforgeBundle:Default:logout }

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
