<?php

namespace Crudforge\CrudforgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository{
    
    public function getUsersCount(){
        return $this->createQueryBuilder()
              ->select('COUNT(u)')
              ->from('Users', 'u')
              ->getQuery()
              ->getSingleScalarResult();
        
    }
    
    public function getSchemasCount(){
        return $this->createQueryBuilder()
              ->select('COUNT(d)')
              ->from('Dcoument', 'd')
              ->getQuery()
              ->getSingleScalarResult();
    }
}
