<?php

namespace Crudforge\CrudforgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharesRepository extends EntityRepository
{
}
